### ISSUE TITLE
Identity information not visible

### ISSUE THREAD

**Issue by laufwerkfehler** [nerdhaus/eldrich#21]
When logged in as end user, player character identity information is not visible on edit page.

**Comment by eaton** [comment]
Turned out to be a permissions issue with the small component sub-entities used to store equipped weapons, morph instances, identity information, and similar bits. People can always edit THEIR OWN, but with some of the initially imported characters (like the Whiskey PCs), they were imported by the system user and then reassigned to the players. The small component entities that make up some of the NPC/PC details didn't change ownership, and boomf.

For the time being, I've just ensured anyone with edit rights for a container entity (like an NPC) can also edit *any* component entity, which is pretty coarse but works okay. In the future I'll need to intercept save events on container entities and make sure that any sub-entities' owners are updated at the same time.
